### PR TITLE
Request focus after submitting

### LINKED ISSUE #60: Flutter sample's text input loses focus after submission
Repro steps:

1. Run the Flutter sample.
2. Type text and press `Enter`

Expected result: the text input stays focused after the response is shown
Actual result: the text input loses focus after the response is shown

### PR DESCRIPTION
**Pull request by johnpryan**
This adds a FocusNode to the text field that will request focus after a chat message is submitted.

cc: @loic-sharma

fixes #60

### CODE REVIEW

File: samples/flutter_app/lib/main.dart [hunk 1]
```diff
@@ -68,10 +68,11 @@ class ChatWidget extends StatefulWidget {
 }
 
 class _ChatWidgetState extends State<ChatWidget> {
-  final ScrollController _controller = ScrollController();
   late final GenerativeModel _model;
   late final ChatSession _chat;
-  late final _textController = TextEditingController();
+  final _scrollController = ScrollController();
```
Comment (devoncarew) [inline samples/flutter_app/lib/main.dart:73]: I'd keep the types for the fields (though more importantly, I'd be consistent about using or not using field types in the sample).

**Review by devoncarew — APPROVED** [review]
The Flutter change lgtm (though, I'm curious - where is the focus going after we hit enter, that we have to re-request it?).

**Comment by devoncarew** [comment]
> The default text field behavior is to unfocus after `onSubmitted` happens. You can put a debugLabel (`TextField`)on the focus node and call `debugDumpFocusTree()` to see what's focused. It looks to me like the text field is unfocusing: https://docs.flutter.dev/ui/interactivity/focus#unfocusing
> 

Thanks for the investigation!
